import {
  Key,
  Plus,
  RefreshCw,
  Copy,
  Info,
  CheckCircle,
  Search,
  Building,
  Calendar,
  Globe,
  FileText,
  Shield,
  AlertCircle,
  Settings,
  Users,
  CreditCard,
  Hash,
  Lock,
  ChevronDown,
  Sun,
  Moon,
} from 'lucide-react';

export const Icons = {
  Key: Key,
  Plus: Plus,
  RefreshCw: RefreshCw,
  Copy: Copy,
  Info: Info,
  CheckCircle: CheckCircle,
  Search: Search,
  Building: Building,
  Calendar: Calendar,
  Globe: Globe,
  FileText: FileText,
  Shield: Shield,
  AlertCircle: AlertCircle,
  Settings: Settings,
  Users: Users,
  CreditCard: CreditCard,
  Hash: Hash,
  Lock: Lock,
  ChevronDown: ChevronDown,
  Sun: Sun,
  Moon: Moon,
};

export default Icons;
